const Strings = {
  welcome: 'Bem-vindo ao FIPE Search!',
  info: 'Aqui você pode consultar dados da FIPE de forma fácil. Basta apenas informar as especificações como marca, modelo e ano.',
  selectTheSpecifications: 'selecione as especificações',
  search: 'buscar',
  brand: 'marca',
  model: 'modelo',
  year: 'ano',
  brands: 'marcas',
  models: 'modelos',
  years: 'anos',
  FIPESearch: 'FIPE Search',
  ok: 'ok',
  ErrorToSearchBrandsFromApi: 'Erro ao buscar marcas da API!',
  ErrorToSearchModelsFromApi: 'Erro ao buscar modelos da API!',
  ErrorToSearchYearsFromApi: 'Erro ao buscar anos da API!',
  ErrorToSearchInfoFromApi: 'Erro ao buscar informações do veículo na API!',
  cleanFields: 'limpar campos',
  selectFieldsInOrder:
    'Informe os campos em ordem! Primeiro a marca, em segundo o modelo e em terceiro o ano.',
  informations: 'informações',
  codeFipe: 'código fipe',
  carType: 'tipo de veículo',
  value: 'valor',
  fuel: 'combustível',
  mothReference: 'mês referência',
  acronymFuel: 'sigla do combustível',
};

export default Strings;
